<?php

return array(
  'admin_role' => 'Admin',
  'discord_invite' => 'https://discord.gg/roleplaymeetsreborn',
  'support_email' => 'support@roleplaymeets.com',
  'site_name' => 'Roleplay Meets',
  'site_slogan' => 'Where roleplayers meet',
  'owner' => 188647277181665280,
  'banned_words' => ["aspie", "dickgirl", "dickgirl", "dyke", "Eskimo", "fag", "faggot", "Gipsy", "Hermie", "jap", "kike", "loli", "loli-con", "lolicon", "N*gga", "N*gger", "nig", "nigersaurus", "nigg", "Nigga", "Nigger", "paki", "pedophile", "r4p3", "r4pe", "rap3", "Rape", "redskins", "retard", "retarded", "r*tard", "r*tarded", "Shemale", "shota", "shota-con", "shotacon", "spic", "towel-head", "tranny", "wet back"],
  'nsfw_words' => [
    "3+ Penetration", "Adultery", "Aftercare", "Age Differences", "Age Progression", "Age Regression", "Ageplay", "Ahegao", "All the Way Through", "Pregnancy", "Amphibians", "Amputees", "Fisting", "Anal Pregnancy", "Anal Prolapse", "Anal Sex", "Anal Training", "Anal Virginity", "Anatomically Correct", "Androgyny", "Angels", "Aphrodisiacs", "Ass to Mouth", "Ass Worship", "Auto-Fellatio", "Bad Ends", "Ballbusting", "Barbed Cocks", "Bathroom Control", "Begging", "Belching / Burping", "Belly Fucking", "Belly Play", "Bimbofication", "Birthing", "Biting", "Blindfolds", "Bloodplay", "Blueberrification",
    "Body Hair",
    "Body Part Transformation",
    "Body Swapping",
    "Body Writing",
    "Bovines",
    "Branding",
    "Breast*",
    "Breeding",
    "Bukkake",
    "Burning",
    "Caging",
    "Cannibalism",
    "Castration",
    "Cervical Penetration",
    "Chastity",
    "Choking",
    "Clit Play",
    "Clothed Sex",
    "Cock*",
    "Coercion / Blackmail",
    "Coiling",
    "Competition",
    "Condoms",
    "Consensual",
    "Corruption",
    "Creampie",
    "Crossdressing",
    "Crotch Sniffing",
    "Cuckolding",
    "Cum",
    "Cunnilingus",
    "Dating",
    "Death",
    "Degradation",
    "Diapers",
    "Dirty Feet",
    "Dirty Talking",
    "Docking",
    "Double Penetration",
    "Alcohol",
    "Drug*",
    "Dub-Consensual",
    "Ear Play",
    "Electric Toys",
    "Emasculation",
    "Enemas",
    "Equines",
    "Excessive Precum",
    "Excessive Semen",
    "Execution / Murder",
    "Exhibitionism",
    "Exotic Cocks",
    "Exotic Species",
    "Extreme Humiliation",
    "Extreme Musk",
    "Extreme Pregnancy",
    "Extreme Tightness",
    "Face Slapping",
    "Face-Fucking",
    "Face-Sitting",
    "Farting",
    "Fat Play",
    "Felching",
    "Fellatio (Performing)",
    "Fellatio (Receiving)",
    "Femdom",
    "Feminization",
    "Filth",
    "Fingering",
    "Fingers in Mouth",
    "Flaccid Play",
    "Whipping",
    "Food Play",
    "Foot Play",
    "Footgear Worship",
    "Footjobs",
    "Force Feeding",
    "Forced Clotheswearing",
    "Forced Growth",
    "Forced Incest",
    "Forced Nudity",
    "Foreplay",
    "Foreskin Worship",
    "Frotting",
    "Gags",
    "Gangbangs",
    "Gaping (Anal)",
    "Gaping (Vaginal)",
    "Gender Transformation",
    "Genital / Nipple Piercings",
    "Genital Torture",
    "Glasses",
    "Gore",
    "Growth",
    "Growth (Macro)",
    "Hair Pulling",
    "Hand Cuffs",
    "Hand Play",
    "Handjobs",
    "Hard Cum Facials",
    "Heat / Rut",
    "Heavily Excessive Precum",
    "Heavily Excessive Semen",
    "Heavy / Extreme Bondage",
    "Hermaphrodites",
    "Horns",
    "Horror",
    "Hotdogging",
    "Human Cocks",
    "Humanoids",
    "Humans",
    "Humiliation",
    "Humor / Comedy",
    "Hyaenidae",
    "Hypnotism / Mind Control",
    "Ice",
    "Immobilization (Bondage)",
    "Immobilization (Size)",
    "Impalement",
    "Impotence",
    "Impregnation",
    "Inanimate Object Transformation",
    "Incest",
    "Infantilism",
    "Inflatables",
    "Inflation (Heavy / Extreme)",
    "Inflation (Light / Medium)",
    "Informality",
    "Insects / Arachnids",
    "Instant Hookups",
    "Intelligent Characters",
    "Intercrural Sex",
    "Internal Cumshots",
    "Interracial",
    "Kemonomimi",
    "Kidnapping",
    "Kissing",
    "Knotted Cocks",
    "Knotting",
    "Lactation",
    "Latex",
    "Collar",
    "Leather",
    "Licking",
    "Light / Medium Bondage",
    "Lima Syndrome",
    "Living Insertions",
    "Macrophilia",
    "Magic Users",
    "Marking",
    "Marsupials",
    "Masculinity",
    "Masks",
    "Massages",
    "Master / Pet",
    "Master",
    "slave",
    "Masturbation",
    "Medical Play",
    "Mega Macro",
    "Menses",
    "Mental Torture",
    "Messy",
    "Microphilia",
    "Moobs",
    "Muscle Growth",
    "Muscle Worship",
    "Muscular Characters",
    "Mutilation",
    "My Little Pony",
    "Natural Musk",
    "Navel Play",
    "Necrophilia",
    "Nightclubs / Bars",
    "Nipple Penetration",
    "Non-Standard Penetration",
    "Nonbinary",
    "Nonconsensual",
    "non-con",
    "Nullification",
    "Nursing",
    "Objectification",
    "Objectophilia",
    "Older Characters",
    "Oral Fixation",
    "Oral Sex (Giving)",
    "Oral Sex (Receiving)",
    "Oral Virginity",
    "Orcs",
    "Orgasm Control / Denial",
    "Orientation Play",
    "Original Characters",
    "Oviposition",
    "Parasites",
    "Paw Play",
    "Pegging",
    "Photograph References",
    "Photography / Videotaping",
    "Physical Restraints",
    "Piercing",
    "Piss Enemas",
    "Plants",
    "Pleasure Control / Denial",
    "Plot Twists",
    "Pokémon",
    "Polyamory",
    "Popping",
    "Possessiveness / Jealousy",
    "Potions / Injections",
    "Powerbottoming",
    "Predator Species",
    "Pregnancy",
    "Prehensile Cocks",
    "Premature Ejaculation",
    "Prey Species",
    "Procyonidae",
    "Prostate Play",
    "Prostitution",
    "Pseudo-rape",
    "Pubic Hair",
    "Public Humiliation",
    "Puppy / Pony Play",
    "Pussy Worship",
    "Quadrupeds",
    "Queefing",
    "Racism",
    "Realism",
    "Realistic Cum",
    "Reptiles",
    "Rimming (Giving)",
    "Rimming (Receiving)",
    "Risk of Pregnancy",
    "Robots, Cyborgs, Androids",
    "Rodents / Murines",
    "Role Reversal",
    "Sadism / Masochism",
    "Scat",
    "Scat Torture",
    "Scratching",
    "Sensory Deprivation",
    "Sentient Cocks",
    "Sex Driven",
    "Sex Toys",
    "Sexism",
    "Sexual Exhaustion",
    "Sexual Frustration",
    "Sexual Pain",
    "Sexual Restraints",
    "Sexual Torture",
    "Sexy / Slutty Clothing",
    "Shaving",
    "Sheath Play",
    "Sheaths",
    "Shemales",
    "Shooting Precum",
    "Shorter Characters",
    "Shrinking",
    "Size Differences (1-3 Feet)",
    "Size Differences (Micro / Macro)",
    "Skinny Characters",
    "Slice of Life",
    "Slime / Goo Characters",
    "Slob",
    "Sloppy Seconds",
    "Small Breasts",
    "Small Cocks",
    "Small Dom / Big Sub",
    "Smegma",
    "Smoking",
    "Snowballing",
    "Socks / Stockings",
    "Soft Cum Facials",
    "Soiling",
    "Somnophilia",
    "Sounding",
    "Spanking",
    "Species Transformation",
    "Speciesism",
    "Speech Restrictions",
    "Squirting",
    "STDs",
    "Stockholm Syndrome",
    "Stomach Bulging",
    "Story Driven",
    "Storytelling (Narrator)",
    "Storytelling (Player)",
    "Strap-ons",
    "Strip Tease",
    "Stuckage",
    "Superheroes / Villains",
    "Supernatural Transformation",
    "Suspension Play",
    "Sweat",
    "Tail Pulling",
    "Tails",
    "Tailsex",
    "Taller Characters",
    "Tantric Sex",
    "Tattoos / Body Art",
    "Teasing",
    "Teeth Play",
    "Tentacles",
    "Thick / Sticky Cum",
    "Throat Penetration",
    "Tickling",
    "Titfucking",
    "Tomboys",
    "Transformation",
    "Transgender",
    "Tribadism / Scissoring",
    "Twinks",
    "Twins / Clones",
    "Udders",
    "Unbirthing",
    "Uncut Cocks",
    "Underage Characters",
    "Underwear",
    "Underwear Bulges",
    "Uniforms",
    "Unusual Semen",
    "Unwashed Musk",
    "Urethra Play",
    "Vaginal",
    "Vagina",
    "Vaginal Virginity",
    "Sex",
    "Verbal Abuse",
    "Violence",
    "Voluptuousness",
    "Vomiting",
    "Vore",
    "Voyeurism",
    "Wardrobe Malfunctions",
    "Watersports",
    "Wax Play",
    "Weapon Play",
    "Weight Loss",
    "Wetting",
    "Wound Fucking",
    "Xeno / Alien",
    "Zoophilia"
  ],
);
